about:
  home: http://gitub.com/UV-CDAT/image-compare
package:
  name: image-compare
  version: 1.0.3
requirements:
  build:
  - python
  - setuptools
  - nodejs
  run:
  - python
  - jinja2
source:
  git_rev: master
  git_url: git://github.com/UV-CDAT/image-compare.git
